// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndkcipdioczeuafjersl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ka2NpcGRpb2N6ZXVhZmplcnNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5MzE4ODUsImV4cCI6MjA0OTUwNzg4NX0.p5D-BnrmAz8E8CUjezxWzSixpQsMHSAuDL9Qz-V4c68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);